-- MySQL Script generated by MySQL Workbench
-- Sat Nov 17 18:12:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `final` ;

-- -----------------------------------------------------
-- Table `final`.`territories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`territories` ;

CREATE TABLE IF NOT EXISTS `final`.`territories` (
  `name` VARCHAR(50) NOT NULL,
  `occupiedBy` VARCHAR(50) NULL DEFAULT NULL,
  `numTroops` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`name`),
  INDEX `occupiedUsername_idx` (`occupiedBy` ASC) VISIBLE,
  CONSTRAINT `occupiedUsername`
    FOREIGN KEY (`occupiedBy`)
    REFERENCES `final`.`users` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `final`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`users` ;

CREATE TABLE IF NOT EXISTS `final`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(500) NULL DEFAULT NULL,
  `fname` VARCHAR(45) NULL DEFAULT NULL,
  `lname` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `playing` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
